apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-webhook-configmap
data:
  volume_patch: '{"name":"internal-tls","secret":{"secretName":"internal-tls","defaultMode":420}}'
  container_patch: '{"name":"sidecar","image":"fanzhan1/fluent:1.10-plugin-script","securityContext":{"runAsNonRoot":true},"resources":{"requests":{"memory":"100Mi","cpu":"100m"},"limits":{"memory":"250Mi","cpu":"250m"}},"imagePullPolicy":"IfNotPresent","volumeMounts":[{"name":"varlog","mountPath":"/var/log"},{"name":"internal-tls","mountPath":"/etc/internal-tls"}]}'
  #cp.stg.icr.io/cp/watson/auditing/audit-sidecar:0.1.0
  #cp.stg.icr.io/cp/watson/auditing/rsyslog-hari:v0.0.1